networks:
  job-flow-network:
    external: true

volumes:
  jobflow-user-pgdata:
  jobflow-user-redisdata:

services:
  jobflow-user-service:
    build:
      context: .
    container_name: jobflow-user-service
    env_file:
      - .env
    networks:
      - job-flow-network
    ports:
      - "8080:8080"
    depends_on:
      jobflow-user-db:
        condition: service_healthy
      jobflow-user-redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

  jobflow-user-db:
    image: postgres:latest
    container_name: jobflow-user-db
    networks:
      - job-flow-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - jobflow-user-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

  jobflow-user-redis:
    image: redis/redis-stack:latest
    container_name: jobflow-user-redis
    networks:
      - job-flow-network
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - jobflow-user-redisdata:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
