name: Job Tracker Service CI

on:
  push:
    branches:
      - 'feature/**'
    paths:
      - 'job-tracker-service/**'
  pull_request:
    branches:
      - 'develop'
    paths:
      - 'job-tracker-service/**'

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: job-tracker-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build project
        run: mvn clean package

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: job-tracker-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run unit tests
        run: mvn test

  integration-tests:
    name: Run integration tests and generate coverage
    runs-on: ubuntu-latest
    needs: unit-tests
    defaults:
      run:
        working-directory: job-tracker-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Docker
        run: docker --version

      - name: Set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run integration tests
        run: mvn verify

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: target/site/jacoco/jacoco.xml
          flags: job-tracker-service
          name: job-tracker-service-coverage
          fail_ci_if_error: true