name: User Service CI/CD

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'user-service/**'

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: user-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build project
        run: mvn clean package

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: user-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run unit tests
        run: mvn test

  integration-tests:
    name: Run integration tests and generate coverage
    runs-on: ubuntu-latest
    needs: unit-tests
    defaults:
      run:
        working-directory: user-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Docker
        run: docker --version

      - name: Set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run integration tests
        run: mvn verify

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: target/site/jacoco/jacoco.xml
          flags: user-service
          name: user-service-coverage
          fail_ci_if_error: true

  docker-build-push:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    needs: integration-tests
    defaults:
      run:
        working-directory: user-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./user-service
          file: ./user-service/Dockerfile
          push: true
          tags: malyga99/user-service:latest